spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/catalog
    username: catalog_user
    password: catalog_pass

  data:
    redis:
      host: localhost
      port: 6379
      time-to-live: 60s

    cache:
      type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true